### ISSUE TITLE
Request : User field limited to members of group(s)

### ISSUE THREAD

**Issue by cjohnsonuk** [cosmocode/dokuwiki-plugin-struct#281] opened 2017-03-27 11:45 UTC
Is it possible to limit the options for a field type of "users" to only those that are in a specified group (or groups). Eg I'd like to be able to specify a member of the board from a drop down but at the moment it shows all users.  I could create this as a manually managed drop down for the board members but there are other groups that are changed more often for which this could be a problem.  We currently get our groups through AD where they are managed

**Comment by iainhallam** [comment] 2022-01-22 05:10
This is a duplicate of #240.

**Closed** 2023-08-03 18:49 UTC
Labels: duplicate
