### ISSUE TITLE
dynfilters don't work if aggregation has "filteror"

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#394] opened 2018-04-20 11:29 UTC
dynfilters don't work in this struct aggregation:

```
---- struct table ----
schema:     pkg
sort:       name, vers
cols:       name, vers, add-ons, module, comment, url, service-url
filter:     distro = CentOS
filteror:   distro = any
dynfilters: yes
----
```

even if a filter is given, the complete table is printed.  This aggregation filters correctly:
```
---- struct table ----
schema:     pkg
sort:       name, vers
cols:       name, vers, add-ons, module, comment, url, service-url
filter:     distro = CentOS
dynfilters: yes
----
```

- DokuWiki version: Release 2017-02-19e "Frusterick Manners" 
- struct plugin version: 2018-01-18

Maybe similar or related to #378?

**Comment by fthommen** [comment] 2018-10-04 18:50
Any chance, that someone could have a look at this issue?

**Comment by splitbrain** [comment] 2019-01-10 15:55
duplicate of #378

**Closed by splitbrain** 2019-01-10 15:55 UTC
