### ISSUE TITLE
CSV Export tab broken styles in Firefox

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#210] opened 2016-11-14 11:27 UTC
As reported in #208 the styling of the CSV export tab is wrong on firefox.

![screenshot](https://cloud.githubusercontent.com/assets/2620833/20207941/ecc4a358-a7ea-11e6-845c-968d9fc09122.jpg)

**Comment by splitbrain** [comment] 2016-11-14 11:35
@stvoigt I can't reproduce the styling problem. What template do you use?

**Comment by micgro42** [comment] 2016-11-14 11:43
It is claimed to be broken on the Extended Support Release (ESR) of Firefox, i.e. version 45.4.0 released in March 2016.

Maybe there some CSS is not supported, which works with the current Firefox?

**Comment by splitbrain** [comment] 2016-11-14 12:26
I tested with Firefox 45.0 but still can't reproduce.

![download](https://cloud.githubusercontent.com/assets/86426/20264853/dfe47f20-aa6d-11e6-8eee-33ff6f033876.png)

**Comment by stvoigt** [comment] 2016-11-14 12:39
ICKE 2.0 Template...

**Comment by micgro42** [comment] 2016-11-14 12:57
I don't think we should fix it in the struct-plugin, because the cause is the ICKE-template having suboptimal styles...

I could add a fix for this to the ICKE-Template?

**Comment by splitbrain** [comment] 2016-11-14 13:13
agreed. we should fix it in the template

**Closed** 2016-11-14 15:31 UTC
Labels: bug
