### ISSUE TITLE
Option to make field part of rendered page

### ISSUE THREAD

**Issue by ahaituki** [cosmocode/dokuwiki-plugin-struct#320] opened 2017-07-15 09:03 UTC
I'm contemplating the switch from Data to Struct. I'm kind of hoping for an easy migration, but that's beside the point here. The main reason for making this switch, in my case, would be to separate data from content. That would solve a lot of problems in itself, like using GitHub for sync and collaboration, without confusing people. However, I'm still left with syntax from the Title, Croissant, and Description plugins, and possibly more metadata to follow later.

I'm not sure if this is within the scope of Struct, but an option to make a field part of the rendered page would solve the remaining challenge. For instance, a text field with pre `{{description>` and post `}}`, would make it easy to specify a description for the page, without touching content. Similarly, content contributors could be set to not have rights to change title, description, etc.

I have wanted this functionality for some time, but didn't see any possibility for it until Struct came along and separated data from content. I hope I have expressed myself clear enough.

**Comment by iainhallam** [comment] 2018-01-26 14:04
There's the structsection plugin, which might be a basis for what you want to do.

**Comment by splitbrain** [comment] 2019-04-01 12:15
this seems to be a duplicate of #438

**Closed by splitbrain** 2019-04-01 12:15 UTC
