### ISSUE TITLE
Date-Picker does not work

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#375] opened 2018-01-26 13:53 UTC
I have two different schemas with date types. In one schema the date picker works. With the attached schema the date picker does not work, i.e. it does not react on clicking the specific date (nothing happens). I can switch between months, but cannot select the date via the picker. I deactivated all other fields and I can select the date via date-picker. When I activate the first text field, the date picker does not work.

Since today (after updating to the latest struct plugin) there is a new bug in using the date picker:
1) when using two date types: I chose a date in the second date type/picker the result is inserted into the first date type field and not the second plus:
2) when editing an existing date the year is inserted twice, e.g. selecting 2018-01-26 is becoming 20182018-01-26

I am using the latest dw- and struct plugin version. Firefox ESR 52.5.2 (32-Bit)

My schema definition (json not attacheable):
```
{
    "structversion": "2018-01-18",
    "schema": "events",
    "id": "144",
    "user": "voigt",
    "config": {
        "allowed editors": "",
        "label": {
            "de": "Veranstaltungsdaten"
        }
    },
    "columns": [
        {
            "colref": 1,
            "ismulti": false,
            "isenabled": true,
            "sort": 10,
            "label": "name",
            "class": "Text",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "prefix": "",
                "postfix": "",
                "label": {
                    "de": "Veranstaltungsname"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 2,
            "ismulti": false,
            "isenabled": true,
            "sort": 20,
            "label": "location",
            "class": "Text",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "prefix": "",
                "postfix": "",
                "label": {
                    "de": "Veranstaltungsort"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 3,
            "ismulti": false,
            "isenabled": true,
            "sort": 30,
            "label": "start",
            "class": "Date",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "format": "Y\/m\/d",
                "prefilltoday": false,
                "label": {
                    "de": "Start"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 4,
            "ismulti": false,
            "isenabled": false,
            "sort": 40,
            "label": "end",
            "class": "Date",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "format": "Y\/m\/d",
                "prefilltoday": false,
                "label": {
                    "de": "Ende"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 6,
            "ismulti": true,
            "isenabled": true,
            "sort": 60,
            "label": "team",
            "class": "User",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "existingonly": true,
                "autocomplete": {
                    "fullname": true,
                    "mininput": 2,
                    "maxresult": 5
                },
                "label": {
                    "de": "Teilnehmer (intern)"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 7,
            "ismulti": false,
            "isenabled": false,
            "sort": 70,
            "label": "partner",
            "class": "Page",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "usetitles": false,
                "autocomplete": {
                    "mininput": 2,
                    "maxresult": 5,
                    "namespace": "partner",
                    "postfix": "start"
                },
                "label": {
                    "de": "Veranstalter"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 8,
            "ismulti": false,
            "isenabled": true,
            "sort": 80,
            "label": "type",
            "class": "Dropdown",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "values": "eigene, externe",
                "label": {
                    "de": "Art"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 11,
            "ismulti": false,
            "isenabled": true,
            "sort": 85,
            "label": "contribution",
            "class": "Lookup",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "schema": "eventtype",
                "field": "type",
                "label": {
                    "de": "Beitrag"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 12,
            "ismulti": false,
            "isenabled": true,
            "sort": 86,
            "label": "service",
            "class": "Page",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "usetitles": true,
                "autocomplete": {
                    "mininput": 2,
                    "maxresult": 5,
                    "namespace": "leistungen:",
                    "postfix": ":start"
                },
                "label": {
                    "de": "Leistung"
                },
                "hint": {
                    "de": "Bezug zu konkreter Leistung (Autovervollst\u00e4ndigung nach 2 Zeichen)"
                }
            }
        },
        {
            "colref": 13,
            "ismulti": false,
            "isenabled": true,
            "sort": 87,
            "label": "workpackage",
            "class": "Page",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "usetitles": true,
                "autocomplete": {
                    "mininput": 2,
                    "maxresult": 5,
                    "namespace": "interne:arbeitspakete:",
                    "postfix": ""
                },
                "label": {
                    "de": "AP"
                },
                "hint": {
                    "de": "Bezug zu Arbeitspaket (Autovervollst\u00e4ndigung nach 2 Zeichen)"
                }
            }
        },
        {
            "colref": 9,
            "ismulti": false,
            "isenabled": true,
            "sort": 90,
            "label": "participants",
            "class": "Decimal",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "min": 0,
                "max": "",
                "roundto": "-1",
                "decpoint": ".",
                "thousands": "\u202f",
                "trimzeros": true,
                "prefix": "",
                "postfix": "",
                "label": {
                    "de": "Anz. Teilnehmer"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 5,
            "ismulti": false,
            "isenabled": true,
            "sort": 100,
            "label": "internet",
            "class": "Url",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "autoscheme": "https",
                "prefix": "",
                "postfix": "",
                "label": {
                    "de": "Homepage"
                },
                "hint": {
                    "de": ""
                }
            }
        },
        {
            "colref": 10,
            "ismulti": true,
            "isenabled": true,
            "sort": 100,
            "label": "estimated",
            "class": "Checkbox",
            "config": {
                "visibility": {
                    "inpage": true,
                    "ineditor": true
                },
                "values": "ja, nein",
                "label": {
                    "de": "TN-Zahl gesch\u00e4tzt?"
                },
                "hint": {
                    "de": ""
                }
            }
        }
    ]
}
```

**Comment by micgro42** [comment] 2018-01-26 15:28
The second bug was introduced by #363 and should be fixed by #374. I'll have a look at the first bug you mention.

**Comment by annda** [comment] 2019-04-03 15:26
I am unable to reproduce any of the bugs (Chrome and Firefox). @stvoigt Can you please check if they have already been fixed, as suggested by @micgro42?

**Comment by annda** [comment] 2019-10-15 08:35
closing via #466

**Closed by annda** 2019-10-15 08:35 UTC
Labels: bug
