### ISSUE TITLE
Autocomplete broken for inline-editor on multifield

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#350] opened 2017-11-13 20:19 UTC
The auto-complete is broken at least in the following conditions:
- use of the inline-editor
- a multi-field
- the field has the type tag

The error message is: `No column provided`

With the network view I can confirm that there is indeed no column in the ajax request.

It seems that the following line is supposed to get the column name:
https://github.com/cosmocode/dokuwiki-plugin-struct/blob/057f6e9e4593101d841778f86c41e7dd48355996/script/EntryEditor.js#L60

`this.element[0]` seems the be the input element. However there is no `div.field`. Instead from the inspector I can see that the html is as follows:

```html
<div class="struct_inlineditor" style="top: 1420.75px; left: 711.333px;">
<form>
<label data-column="journal.Personen" for="struct__5a09fbc5867d9"></label>
<div class="multiwrap">
<input name="entry" class="struct_page struct_autocomplete ui-autocomplete-input ui-autocomplete-loading" id="struct__5a09fbc5867d9" autocomplete="off">
</div>
<small>Enter multiple values separated by commas.</small>
<div class="no">
<input name="sectok" value="a65b73cdb636cbff17d4b1cc3c1e95b5" type="hidden">
</div>
<input name="pid" value="appreciation:2017-11-11" type="hidden">
<input name="field" value="journal.Personen" type="hidden">
<input name="call" value="plugin_struct_inline_save" type="hidden">
<div class="ctl">
<button type="submit">Save</button>
<button>Cancel</button>
</div>
</form>
<div class="err" style="display: none;"></div>
</div>
```

**Comment by rottaran** [comment] 2018-01-03 23:21
Was fixed with pull request #362. Thank you for the analysis. I should have read this before searching the cause :)

**Closed** 2018-01-04 12:22 UTC
Labels: bug
