### ISSUE TITLE
Guide to transfer to struct from older plugins (e.g. strata or data)

### ISSUE THREAD

**Issue by simon-r-white** [cosmocode/dokuwiki-plugin-struct#626] opened 2023-01-06 10:19 UTC
The strata-plugin is no longer maintained: [https://www.dokuwiki.org/plugin:strata](). (Equally the data-plugin now recommends using struct [https://www.dokuwiki.org/plugin:strata]()).

For those of us who have existing wikis using (for me specifically the strata-plugin), is there a viable way to transition to using the struct-plugin?

Manually editing hundreds of pages would be... not great. Just wondered if anyone has a guide/tutorial/thoughts on how to transition from strata to struct?

**Comment by splitbrain** [comment] 2023-02-08 15:48
duplicate of #42

**Closed by splitbrain** 2023-02-08 15:48 UTC
