### ISSUE TITLE
builtin search dokuwiki

### ISSUE THREAD

**Issue by FiC5020** [cosmocode/dokuwiki-plugin-struct#582] opened 2021-07-21 07:48 UTC
Hello,
i'm using struct for some lists in dokuwiki, which work's great.
But the entry can not be found with the builtin search of dokuwiki.

Could you tell what I'm doing wrong?

Thanks in advance
Christian

**Comment by splitbrain** [comment] 2021-07-21 08:03
Thanks for opening the issue. Unfortunately your issue does not contain enough information. Please try to provide as much info as possible, generally following these three main questions:

* What did you do?
* What did you expect to happen?
* What happened instead?

Please also describe what steps you took to analyze the issue and what (failed) attempts you made to fix the problem yourself.

Your issue should contain everything that might help in analyzing and reproducing the issue. That includes but isn't limited to:

* versions of the involved software
* exact error messages
* debug logs (also check your JavaScript console for web related issues)

Thanks for your help.

PS: You may want to refer to [How to Ask Questions the Smart Way](http://www.catb.org/esr/faqs/smart-questions.html) for more tips on improving your issue creation game ;-)

**Comment by FiC5020** [comment] 2021-07-21 12:09
> What did you du

I install dokuwiki and struct for work with some list. this works fine

> What did you expect to happen?
To see the entry of struct in the builtin search of Dokuwiki. I only see the entries on the page but not the entries of struct in the database.

> What happened instead?

I only see the entries from pages with created in Wikitext and not in the database.

My steps to find the problem myself. Activate debugging and and use the paramenter do=check
![image](https://user-images.githubusercontent.com/51019826/126486110-b2a4dfe1-1a86-4c3a-936e-0f607051182c.png)

Errormessage other nothing there, simple no search results.

I install an a new dokuwiki instance for checking.

**Comment by splitbrain** [comment] 2021-07-22 06:58
closing this because no info on how to reproduce was given.

**Closed by splitbrain** 2021-07-22 06:58 UTC
