### ISSUE TITLE
Importing CSV does not work for "lookup" type fields

### ISSUE THREAD

**Issue by zarhan** [cosmocode/dokuwiki-plugin-struct#325] opened 2017-07-25 05:53 UTC
Hi,

  When importing a CSV file, and one of the target fields is of type "lookup", the database actually has a reference (foreign key) to the lookup target schema. 

  Since exporting a CSV puts the end-value into the field, I thought it would be nice to be able to import lookup values as well.

  I think this issue affects "Dropdown" type as well. Anyway, I modified the end of CSVImporter.php as follows. Not making a patch since I don't exactly know the underlying object model and as you can see, this reeks of copypaste programming, but this allows importing from CSV to fields with lookup type to work.

What it does is check if the class of column is "Lookup". If it is, it then does a search on the actual target schema for the data in the CSV, and changes the "value" to the primary key of that entry. If multiple entries match, it returns the first one (getPids()[0]). 

As you can see, this can probably take a lot of refactoring, and should also be modified to address the "Dropdown" type as well, so this is probably not the best way to do it. This works for us, but it would be nicer to have a better written version by someone who knows how the rest of the code actually works and would make it a generic.

    protected function importLine($line, $single, $multi) {
        // prepare values for single value table
        $values = array();
        foreach($this->columns as $i => $column) {
            if(!isset($line[$i])) throw new StructException('Missing field at CSV line %d', $this->line);
            if($column->isMulti()) {
                // multi values get split on comma
                $line[$i] = array_map('trim', explode(',', $line[$i]));
                $values[] = $line[$i][0];
            } else {
                $values[] = $line[$i];
                if($column->getType()->getClass() == "Lookup") {
                    $lookupcfg = $column->getType()->getAsEntry();
                    $schemainfo = json_decode($lookupcfg[config]);
                    $schema=$schemainfo->{'schema'};
                    $field=$schemainfo->{'field'};
                    $lookupsearch = new Search();
                    $lookupsearch->addSchema($schema);
                    $lookupsearch->addColumn($field);
                    $lookupsearch->addFilter($field, array_pop($values), '=');
                    $lookupsearch->execute();
                    $values[] = $lookupsearch->getPids()[0];
                }
            }
        }

        // insert into single value table (and create pid)
        $this->sqlite->query($single, $values);
        $res = $this->sqlite->query('SELECT last_insert_rowid()');
        $pid = $this->sqlite->res2single($res);
        $this->sqlite->res_close($res);

        // insert all the multi values
        foreach($this->columns as $i => $column) {
            if(!$column->isMulti()) continue;
            foreach($line[$i] as $row => $value) {
                if($column->getType()->getClass() == "Lookup") {
                    $lookupcfg = $column->getType()->getAsEntry();
                    $schemainfo = json_decode($lookupcfg[config]);
                    $schema=$schemainfo->{'schema'};
                    $field=$schemainfo->{'field'};
                    $lookupsearch = new Search();
                    $lookupsearch->addSchema($schema);
                    $lookupsearch->addColumn($field);
                    $lookupsearch->addFilter($field, $value, '=');
                    $lookupsearch->execute();
                    $value = $lookupsearch->getPids()[0];
                }
                $this->sqlite->query($multi, array($pid, $column->getColref(), $row + 1, $value));
            }
        }
    }

**Comment by splitbrain** [comment] 2019-04-01 12:06
This seems to be a duplicate of #357

**Closed by splitbrain** 2019-04-01 12:06 UTC
