### ISSUE TITLE
[Bug Report] Table Aggregation Error: Only One Schema's Data Displayed When Combining Two Schemas

### ISSUE THREAD

**Issue by vvclin-git** [cosmocode/dokuwiki-plugin-struct#683] opened 2023-11-07 06:51 UTC
Given 2 database defined by different schemas (test_a, test_b)

![image.png](https://hackmd.io/_uploads/SkGBiLDQT.png)

The table aggregation combining these 2 schemas only returned data from test_a while test_b data was completely missing.

```
---- struct table ----
schema: test_a, test_b
col: %pageid%, *
----
```
![image.png](https://hackmd.io/_uploads/H1oj6IPQ6.png)

[Possible cause per Andi's post on DokuWiki Forum](https://forum.dokuwiki.org/d/18443-struct-plugin-table-with-lookup/10)
> the problem is probably also related to the assignment checks done in SearchSQLBuilder::addSchemas() despite this being serial data and that limiting that check to $first_table seems kinda bogus anyway.

**References:**
- [original DokuWiki forum post](https://forum.dokuwiki.org/d/18443-struct-plugin-table-with-lookup/)

**Comment by splitbrain** [comment] 2023-11-07 13:16
Okay, my brain was a bit foggy yesterday. Thinking a bit more about it, it's clear why this isn't working, or better why it can't work.

This is trying to join two serial data schemas. Both schemas contain multiple rows of data, where each has the same page id. Doing a join on them would join every row in one table with every row in the other. Clearly not what you want and the reason why you initially had a `test_a.model = test_b.model` filter in there.

Now joining two serial schemas is seems to be weird anyway as both would have to be declared on the same page anyway, since struct only joins on page IDs. Seems not very useful and more like a test setup than real use case.

Joining page data with serial or global data would probably be more helpful. However the problem would remain, without being able to declare additional join conditions it makes no sense.

So this ends up being a duplicate of #269, #285 and #598.

PS: I seem to remember that I had thought of this and somewhere explicitly prevent joins on serial and global data, couldn't find it on a quick glance though.

PPS: having more complex joins would be awesome. But unless someone hires us to implement this, it won't happen.

PPPS: don't ask for a price - I don't know. coming up with a workable concept will take a couple of days - which needs to be paid. if that's still interesting to you, send a mail.

**Closed by splitbrain** 2023-11-07 13:16 UTC

**Comment by vvclin-git** [comment] 2023-11-08 03:36
@splitbrain 
Thank you for the quick reply/action! It clarified a lot of things.
So it seems like it is prohibited to include 2 schemas under the same table aggregation right?
I wonder what is the output of the code mentioned in the struct documentation.
[Schema and Column Selection](https://www.dokuwiki.org/plugin:struct:aggregation#schema_and_column_selection)
![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/15643572/ef64d96b-115c-4c8d-9882-510eaecfebce)
If it still works, could you elaborate in what case the code may work? (i.e. provide more detail about the schema1 and 2 and the output)
Thank you very much.
Wayne

**Comment by splitbrain** [comment] 2023-11-08 08:12
> So it seems like it is prohibited to include 2 schemas under the same table aggregation right?

No. That is a perfectly valid thing to do for *page* schemas. And that's what the example you're quoting refers to.

**Comment by vvclin-git** [comment] 2023-11-09 01:25
> > So it seems like it is prohibited to include 2 schemas under the same table aggregation right?
> 
> No. That is a perfectly valid thing to do for _page_ schemas. And that's what the example you're quoting refers to.

Thank you for the reply, but I am still unable to make it work even with page schemas.

I now have test_a and test_b assigned to the same namespace, and test_c is under another one.

![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/15643572/7850cae2-034e-40db-b801-643dc3691240)

But still, none of the table aggregation involving more than 1 schema works.

![image](https://github.com/cosmocode/dokuwiki-plugin-struct/assets/15643572/3a761a28-0dc2-4424-95f2-a2fe3b0ad0bc)

**Comment by annda** [comment] 2023-11-14 20:40
Everything works as expected. In your screenshots, there is not a single page that has data from more than one schema.

I have updated the documentation to make it clear what multiple schemas are supposed to do: aggregations show pages, **not schemas**. If you define more than one schema, the pages will have to that match all criteria (all schemas).
